JBossESB - TrailBlazer Quote Response Notification

Customer SSN:           $ssn$
Customer Email:         $email$

-- BANK QUOTES RECEIVED --

QUOTE ID:	$quote$
RATE:		$rate$
BANK CODE:	$code$

-- BANK CODES --
0 - success
1 - loan term exceeds the maximum available loan term
2 - invalid SSN
3 - invalid credit score
4 - invalid credit history length
5 - invalid loan term
6 - invalid message
7 - invalid customer ID
